server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Kmdlmm1218.
    url: jdbc:mysql://47.101.49.5:3306/study?useUnicode=true&characterEncoding=UTF-8
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml